"""
Day 17 (part 2): Code quality filtering for Python shards.

Keeps files where:
  - 50 ≤ len(text) ≤ 50,000 chars
  - max line length ≤ 1,000 chars  (drops minified / generated)
  - Shannon entropy ≥ 2.5 bits     (drops low-entropy data dumps)
  - data-literal fraction < 0.4    (drops files that are mostly lists/dicts)
  - not auto-generated (header heuristic)

Usage:
    python data/filter_code.py --in data/dedup_shards/code/train.jsonl.gz \\
                               --out data/filtered/code/train.jsonl.gz
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from data.acquire import iter_shard, write_shard

# ---------------------------------------------------------------------------
# Thresholds
# ---------------------------------------------------------------------------

MIN_CHARS       = 50
MAX_CHARS       = 50_000
MAX_LINE_LEN    = 1_000     # minified files have very long lines
MIN_ENTROPY     = 2.5       # bits; random data has ~8, natural code ~4–5
MAX_DATA_FRAC   = 0.4       # fraction of lines that look like data literals

# ---------------------------------------------------------------------------
# Heuristics
# ---------------------------------------------------------------------------

_GENERATED_HEADER = re.compile(
    r"(?:auto.?generated|do not edit|generated by|code generated|"
    r"this file is generated|autogenerated)",
    re.IGNORECASE,
)

# Lines that are pure data: only digits, commas, brackets, whitespace
_DATA_LINE = re.compile(r"^\s*[\d\s,.\[\]{}()'\"]+\s*$")


def shannon_entropy(text: str) -> float:
    """Compute Shannon entropy in bits per character."""
    if not text:
        return 0.0
    freq = {}
    for ch in text:
        freq[ch] = freq.get(ch, 0) + 1
    n = len(text)
    return -sum((c / n) * math.log2(c / n) for c in freq.values())


def data_literal_fraction(text: str) -> float:
    """Fraction of non-blank lines that look like data literals."""
    lines       = [l for l in text.splitlines() if l.strip()]
    if not lines:
        return 0.0
    data_lines  = sum(1 for l in lines if _DATA_LINE.match(l))
    return data_lines / len(lines)


def max_line_length(text: str) -> int:
    """Length of the longest line."""
    return max((len(l) for l in text.splitlines()), default=0)


def is_generated(text: str) -> bool:
    """True if the file header suggests auto-generation."""
    header = text[:500]
    return bool(_GENERATED_HEADER.search(header))


# ---------------------------------------------------------------------------
# Single-document filter
# ---------------------------------------------------------------------------


def filter_code_doc(doc: dict) -> dict | None:
    """
    Apply all code quality filters to one document.

    Returns the doc unchanged if it passes, or None if it should be dropped.
    """
    text = doc.get("text", "")

    if not (MIN_CHARS <= len(text) <= MAX_CHARS):
        return None

    if max_line_length(text) > MAX_LINE_LEN:
        return None

    if shannon_entropy(text) < MIN_ENTROPY:
        return None

    if data_literal_fraction(text) > MAX_DATA_FRAC:
        return None

    if is_generated(text):
        return None

    return doc


# ---------------------------------------------------------------------------
# Shard pipeline
# ---------------------------------------------------------------------------


def filter_shard(in_path: Path, out_path: Path) -> dict:
    """Filter one code shard. Returns stats."""
    n_in = n_out = 0
    reasons: dict[str, int] = {
        "length": 0, "long_line": 0, "low_entropy": 0,
        "data_literal": 0, "generated": 0,
    }

    def _filtered():
        nonlocal n_in, n_out
        for doc in iter_shard(in_path):
            n_in += 1
            text = doc.get("text", "")

            if not (MIN_CHARS <= len(text) <= MAX_CHARS):
                reasons["length"] += 1
                continue
            if max_line_length(text) > MAX_LINE_LEN:
                reasons["long_line"] += 1
                continue
            if shannon_entropy(text) < MIN_ENTROPY:
                reasons["low_entropy"] += 1
                continue
            if data_literal_fraction(text) > MAX_DATA_FRAC:
                reasons["data_literal"] += 1
                continue
            if is_generated(text):
                reasons["generated"] += 1
                continue

            n_out += 1
            yield doc

    write_shard(_filtered(), out_path)
    dropped  = n_in - n_out
    return {
        "in":       n_in,
        "out":      n_out,
        "dropped":  dropped,
        "drop_pct": dropped / n_in * 100 if n_in else 0.0,
        "reasons":  reasons,
    }


def print_stats(stats: dict) -> None:
    print(f"  {stats['in']:,} → {stats['out']:,} docs "
          f"(dropped {stats['dropped']:,} = {stats['drop_pct']:.1f}%)")
    print("  Drop reasons:")
    for reason, count in stats["reasons"].items():
        if count:
            print(f"    {reason:<15}: {count:,}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Filter Python code shards (Day 17)")
    p.add_argument("--in",  dest="in_path",  required=True, type=Path)
    p.add_argument("--out", dest="out_path", required=True, type=Path)
    return p.parse_args()


if __name__ == "__main__":
    args  = _parse()
    stats = filter_shard(args.in_path, args.out_path)
    print_stats(stats)
